Mtd 40 get capital
gregorusanov/achinova-diary pull request #27
Opened 2023-08-24 17:11 UTC by gilich

1. The method getCapital is added to the countryController, countryHandler, countryService and cityRepository.
2. Methods create and update are modified.
3. New exceptions are created (CityAlreadyExists and CapitalAlreadyExists)

2023-08-24 20:06 UTC, gregorusanov requested changes

2023-08-24 20:06 UTC, gregorusanov commented on src/main/java/com/ghilly/web/handler/CityHandler.java
> +        List<CityDAO> list = cityServiceRest.findAllCitiesWithTheSameName(name);
rewrite it to sql method

2023-08-25 14:10 UTC, gilich commented on src/main/java/com/ghilly/web/handler/CityHandler.java
> +        List<CityDAO> list = cityServiceRest.findAllCitiesWithTheSameName(name);
got it

2023-08-28 10:31 UTC, gregorusanov approved these changes

2023-08-28 10:31 UTC, merged