Feature that let the city and the country names be saved in lower case
gregorusanov/achinova-diary pull request #28
Opened 2023-08-28 12:22 UTC by gilich

2023-09-06 18:50 UTC, gregorusanov requested changes

2023-09-06 18:50 UTC, gregorusanov commented on src/main/java/com/ghilly/web/handler/CountryHandler.java
> +    private void checkNameIsValid(CountryDAO countryDAO) {
please bring only name for country

2023-09-06 18:50 UTC, gregorusanov commented on src/main/java/com/ghilly/web/handler/CountryHandler.java
> +        String nameInLowerCase = countryDAO.getName().toLowerCase();
Set name in lower register before checking

2023-09-06 18:50 UTC, gregorusanov commented on src/test/java/com/ghilly/web/handler/CityHandlerTest.java
> +    private static final String MOSCOW_LOWER_CASE = "moscow";
bad dicion, get MOSCOW and transform it to lower case

2023-09-06 18:50 UTC, gregorusanov commented on src/test/java/com/ghilly/integrationTest/CountryDAORestControllerIntegrationSuccessfulTest.java
> +        int id = Objects.requireNonNull(countryRepository.findByName(countryDAO.getName()).orElse(null)).getId();
revert it

2023-09-06 18:50 UTC, gregorusanov commented on src/test/java/com/ghilly/web/handler/CountryHandlerTest.java
> +    private static final CountryDAO RUS_FOR_SERVICE = new CountryDAO(COUNTRY_ID, NAME_LOWER_CASE);
please rename it

2023-09-07 12:10 UTC, ghilyana commented on src/main/java/com/ghilly/web/handler/CountryHandler.java
> +    private void checkNameIsValid(CountryDAO countryDAO) {
done

2023-09-07 12:10 UTC, ghilyana commented on src/main/java/com/ghilly/web/handler/CountryHandler.java
> +        String nameInLowerCase = countryDAO.getName().toLowerCase();
done

2023-09-07 12:10 UTC, ghilyana commented on src/test/java/com/ghilly/web/handler/CityHandlerTest.java
> +    private static final String MOSCOW_LOWER_CASE = "moscow";
done

2023-09-07 12:10 UTC, ghilyana commented on src/test/java/com/ghilly/web/handler/CountryHandlerTest.java
> +    private static final CountryDAO RUS_FOR_SERVICE = new CountryDAO(COUNTRY_ID, NAME_LOWER_CASE);
done

2023-09-07 12:10 UTC, gilich commented on src/test/java/com/ghilly/integrationTest/CountryDAORestControllerIntegrationSuccessfulTest.java
> +        int id = Objects.requireNonNull(countryRepository.findByName(countryDAO.getName()).orElse(null)).getId();
got it

2023-09-07 12:22 UTC, gregorusanov approved these changes

2023-09-07 12:23 UTC, merged